name: conda_dssp
channels:
  - mx
  - salilab
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argon2-cffi=20.1.0
  - attrs=20.1.0
  - backcall=0.2.0
  - biopython=1.77
  - blas=1.0
  - bleach=3.1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - cffi=1.14.2
  - chardet=3.0.4
  - cryptography=3.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - dssp=3.0.0
  - entrypoints=0.3
  - expat=2.2.9
  - git=2.23.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=2.11.2
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.6
  - jupyter_core=4.6.3
  - jupyterlab=2.2.6
  - jupyterlab_server=1.2.0
  - krb5=1.18.2
  - ld_impl_linux-64=2.33.1
  - libboost=1.67.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - notebook=6.1.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.1.1
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - perl=5.26.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.2.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyzmq=19.0.1
  - readline=8.0
  - reduce=3.24
  - requests=2.24.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
